/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './logger.module';
import * as import2 from './logger.service';
class LoggerModuleInjector extends import0.ɵNgModuleInjector<import1.LoggerModule> {
  _LoggerModule_0:import1.LoggerModule;
  __Logger_1:import2.Logger;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _Logger_1():import2.Logger {
    if ((this.__Logger_1 == null)) { (this.__Logger_1 = new import2.Logger()); }
    return this.__Logger_1;
  }
  createInternal():import1.LoggerModule {
    this._LoggerModule_0 = new import1.LoggerModule();
    return this._LoggerModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.LoggerModule)) { return this._LoggerModule_0; }
    if ((token === import2.Logger)) { return this._Logger_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const LoggerModuleNgFactory:import0.NgModuleFactory<import1.LoggerModule> = new import0.NgModuleFactory<any>(LoggerModuleInjector,import1.LoggerModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2lvdmFubmkvUHJvamVjdHMvYXRlbmRlL2FuZ3VsYXItc3BhL3NyYy9sb2dnZXIvbG9nZ2VyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2dpb3Zhbm5pL1Byb2plY3RzL2F0ZW5kZS9hbmd1bGFyLXNwYS9zcmMvbG9nZ2VyL2xvZ2dlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
